const products = [
  {id:1,name:'KC 38 Sliding Window Frame',sku:'KC-SW38-001',category:'Aluminium Profiles',brand:'KC Aluminium',spec:'38 mm • 6.0 m length',finish:'Silver',stock:'In stock',price:68.50,shape:'profile',badge:'BESTSELLER'},
  {id:2,name:'KC 50 Casement Outer Frame',sku:'KC-CW50-012',category:'Aluminium Profiles',brand:'KC Aluminium',spec:'50 mm • Powder coated',finish:'Black',stock:'In stock',price:92.00,shape:'profile'},
  {id:3,name:'Knauf Standard Plasterboard',sku:'KN-PB-1209',category:'Knauf Plasterboard',brand:'Knauf',spec:'9.5 mm • 1200 × 2400 mm',finish:'Natural',stock:'In stock',price:32.90,shape:'board',badge:'POPULAR'},
  {id:4,name:'Premium Crescent Window Handle',sku:'AC-HDL-228B',category:'Accessories',brand:'Kin Long',spec:'Aluminium • Matte black',finish:'Black',stock:'In stock',price:18.50,shape:'handle'},
  {id:5,name:'Heavy Duty Sliding Door Roller',sku:'AC-RLR-440',category:'Accessories',brand:'Doric',spec:'Double bearing • 80 kg',finish:'Silver',stock:'Low stock',price:26.00,shape:'roller'},
  {id:6,name:'Cordless Rivet Gun 18V',sku:'TL-RG18-02',category:'Tools',brand:'Makita',spec:'2.4–4.8 mm rivets',finish:'Black',stock:'In stock',price:489.00,shape:'tool',badge:'NEW'},
  {id:7,name:'Sikasil® Construction Sealant',sku:'SIKA-CO-WH',category:'Tools',brand:'Sika',spec:'300 ml • Weather resistant',finish:'White',stock:'In stock',price:22.80,shape:'sealant'},
  {id:8,name:'Stainless Steel Friction Stay',sku:'AC-FS-14SS',category:'Accessories',brand:'KC Hardware',spec:'14 inch • SS304',finish:'Silver',stock:'In stock',price:15.50,shape:'hinge'}
];
let enquiry=[products[0],products[4]], state={tab:'All',query:'',finish:'',inStock:false,maxPrice:500};
const grid=document.getElementById('productGrid'), suggestions=document.getElementById('suggestions');
function money(n){return `RM ${n.toFixed(2)}`}
function renderProducts(){let list=products.filter(p=>(state.tab==='All'||p.category===state.tab)&&(p.name+' '+p.sku+' '+p.brand+' '+p.category+' '+p.spec).toLowerCase().includes(state.query.toLowerCase())&&(!state.finish||p.finish===state.finish)&&(!state.inStock||p.stock==='In stock')&&p.price<=state.maxPrice);grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image">${p.badge?`<span class="badge ${p.badge==='NEW'?'new':''}">${p.badge}</span>`:''}<div class="product-shape shape-${p.shape}"></div></div><div class="card-body"><span class="card-brand">${p.brand} · ${p.category}</span><h3>${p.name}</h3><span class="sku">${p.sku}</span><p class="spec">${p.spec}</p><div class="swatches"><i style="background:${p.finish==='Black'?'#283039':p.finish==='White'?'#f8f8f5':p.finish==='Natural'?'#ddd8c9':'#b7c1c7'}"></i><small>${p.finish}</small></div><p class="stock ${p.stock==='Low stock'?'low':''}">● ${p.stock}</p><div class="price-row"><strong>${money(p.price)}</strong><button class="add-btn" onclick="addEnquiry(${p.id})" aria-label="Add ${p.name} to enquiry">+</button></div></div><a class="view-link" href="#" onclick="event.preventDefault();showToast('Product details ready for enquiry')">VIEW DETAILS →</a></article>`).join('');document.getElementById('resultCount').textContent=`Showing ${list.length} product${list.length!==1?'s':''}`;document.getElementById('emptyState').style.display=list.length?'none':'block';grid.style.display=list.length?'grid':'none';renderActiveFilters()}
function renderActiveFilters(){const el=document.getElementById('activeFilters'), items=[];if(state.query)items.push(`Search: ${state.query}`);if(state.finish)items.push(state.finish);if(state.inStock)items.push('In stock');el.innerHTML=items.map(x=>`<button onclick="clearFilters()">${x} ×</button>`).join('')}
function clearFilters(){state={tab:'All',query:'',finish:'',inStock:false,maxPrice:500};document.getElementById('mainSearch').value='';document.getElementById('inStock').checked=false;document.getElementById('priceRange').value=500;document.querySelectorAll('.chips button').forEach(b=>b.classList.remove('selected'));document.querySelectorAll('.tabs button').forEach((b,i)=>b.classList.toggle('active',i===0));renderProducts()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.filter;document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===state.tab));document.getElementById('catalogue').scrollIntoView();renderProducts()});
document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{state.finish=state.finish===b.dataset.finish?'':b.dataset.finish;document.querySelectorAll('.chips button').forEach(x=>x.classList.toggle('selected',x.dataset.finish===state.finish));renderProducts()});
document.getElementById('inStock').onchange=e=>{state.inStock=e.target.checked;renderProducts()};document.getElementById('priceRange').oninput=e=>{state.maxPrice=+e.target.value;renderProducts()};document.getElementById('filterToggle').onclick=()=>document.getElementById('filters').classList.toggle('open');
document.getElementById('mainSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();const matches=products.filter(p=>(p.name+' '+p.sku+' '+p.brand).toLowerCase().includes(q)).slice(0,5);suggestions.innerHTML=q?matches.map(p=>`<button data-name="${p.name}">${p.name}<small>${p.sku}</small></button>`).join(''):'';suggestions.classList.toggle('show',q&&matches.length);suggestions.querySelectorAll('button').forEach(b=>b.onclick=()=>runSearch(b.dataset.name))});
document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();runSearch(document.getElementById('mainSearch').value)};
document.querySelectorAll('.quick-search button').forEach(b=>b.onclick=()=>runSearch(b.textContent));
function runSearch(q){state.query=q;state.tab='All';document.getElementById('mainSearch').value=q;suggestions.classList.remove('show');document.getElementById('catalogue').scrollIntoView();renderProducts()}
function focusSearch(){document.getElementById('mainSearch').focus();document.getElementById('top').scrollIntoView()}
function addEnquiry(id){const p=products.find(x=>x.id===id);if(!enquiry.some(x=>x.id===id))enquiry.push(p);renderEnquiry();showToast('Added to your enquiry list')}
function renderEnquiry(){document.getElementById('enquiryCount').textContent=enquiry.length;document.getElementById('drawerCount').textContent=`${enquiry.length} item${enquiry.length!==1?'s':''}`;document.getElementById('enquiryItems').innerHTML=enquiry.length?enquiry.map(p=>`<div class="enquiry-item"><div class="enquiry-thumb">▣</div><div><b>${p.name}</b><small>${p.sku} · ${p.spec}</small><input type="number" value="1" min="1" aria-label="Quantity" /></div><button onclick="removeEnquiry(${p.id})">×</button></div>`).join(''):'<p>Your enquiry list is empty.</p>';document.getElementById('waLink').href='https://wa.me/60380661288?text='+encodeURIComponent('Hi KC Aluminium, I would like to enquire about:\n'+enquiry.map(p=>'• '+p.name+' ('+p.sku+')').join('\n'))}
function removeEnquiry(id){enquiry=enquiry.filter(p=>p.id!==id);renderEnquiry()}
function openEnquiry(){renderEnquiry();document.getElementById('enquiryDrawer').classList.add('open');document.getElementById('drawerBackdrop').classList.add('open')}
function closeEnquiry(){document.getElementById('enquiryDrawer').classList.remove('open');document.getElementById('drawerBackdrop').classList.remove('open')}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function submitEnquiry(){showToast('Enquiry submitted — we’ll be in touch!');closeEnquiry()}
renderProducts();renderEnquiry();
